package me.lagbug.xprotect.spigot.events;

import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerItemHeldEvent;

import me.lagbug.xprotect.spigot.XProtect;
import me.lagbug.xprotect.spigot.utils.Utils;

/**
 * This class is used to verify the player in the slot captcha 
 *
 * @version 1.0
 */
public class PlayerItemHeld implements Listener {

	//Getting the instance of the main class
	private final XProtect plugin = XProtect.getPlugin(XProtect.class);
		
	@EventHandler
	public void onPlayerItemHeld(PlayerItemHeldEvent e) {
		Player player = e.getPlayer();
		
		//If the player is not in the verificatio process
		if (!plugin.getToVerify().containsKey(player)) {
			return;
		}
		
		//Used to store the current slot
		int slot = -1;
		
		try {
			//The random slot generated by the plugin
			slot = Integer.parseInt(plugin.getToVerify().get(player).replace(plugin.getCode(), ""));
		} catch (NumberFormatException ex) {
			return;
		}
		
		//If the random slot matches the one the player is at, we verify the player
		if (e.getNewSlot() == slot - 1) {
			Utils.captchaSuccess(player);
		}
	}
}